[BRE-101] Remove dept-devops from CODEOWNERS
bitwarden/sm-kubernetes pull request #35
Opened 2024-06-10 12:26 UTC by michalchecinski

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/BRE-101

## 🚧 Type of change

Remove dept-devops from all CODEOWNERS

- 🐛 Bug fix
- 🚀 New feature development
- 🧹 Tech debt (refactoring, code cleanup, dependency upgrades, etc.)
- 🤖 Build/deploy pipeline (DevOps)
- 🎂 Other

## 📔 Objective

Remove dept-devops from all CODEOWNERS, and add `dept-bre` to `.github/workflows/release.yml` as owner.

## 📋 Code changes

- **.github/CODEOWNERS:** Remove dept-devops from all CODEOWNERS, and add 

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-06-10 12:27 UTC, michalchecinski commented
Hold until https://bitwarden.atlassian.net/servicedesk/customer/portal/5/TSD-648 finished.

2024-06-20 14:16 UTC, coltonhurst submitted a review, later dismissed

2024-10-16 18:19 UTC, vgrassia requested changes

2024-10-16 18:19 UTC, vgrassia commented on .github/CODEOWNERS
> +.github/workflows/bump_version.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
```suggestion
.github/workflows/build_ghcr.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
.github/workflows/build.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
.github/workflows/bump_version.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
.github/workflows/release.yml @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
```

2024-10-16 18:19 UTC, vgrassia commented on .github/CODEOWNERS
> +.dockerignore @bitwarden/team-secrets-manager-dev @bitwarden/dept-bre
```suggestion
Dockerfile @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
.dockerignore @bitwarden/dept-bre @bitwarden/team-secrets-manager-dev
```

2024-10-18 15:15 UTC, coltonhurst approved these changes

2024-10-21 13:07 UTC, vgrassia approved these changes

2024-10-21 13:07 UTC, merged